theme: jekyll-theme-minimal
title: Egg Paratha
description: Computational Discussion sessions or something like that. IDK what these Phi@I people do all the time. Probably trying to copy some MIT Club.
